# Ko configuration for kind cluster development
defaultPlatforms:
- linux/amd64
defaultBaseImage: cgr.dev/chainguard/static:latest

# For kind clusters, we build locally and load into the cluster
builds:
- id: ko://github.com/conforma/knative-service/cmd/launch-taskrun
  main: ./cmd/launch-taskrun
