// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	client "sigs.k8s.io/controller-runtime/pkg/client"

	mock "github.com/stretchr/testify/mock"

	runtime "k8s.io/apimachinery/pkg/runtime"

	types "k8s.io/apimachinery/pkg/types"
)

// ControllerRuntimeClient is an autogenerated mock type for the controllerRuntimeClient type
type ControllerRuntimeClient struct {
	mock.Mock
}

type ControllerRuntimeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ControllerRuntimeClient) EXPECT() *ControllerRuntimeClient_Expecter {
	return &ControllerRuntimeClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, obj, opts
func (_m *ControllerRuntimeClient) Create(ctx context.Context, obj client.Object, opts ...client.CreateOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, obj)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Object, ...client.CreateOption) error); ok {
		r0 = rf(ctx, obj, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ControllerRuntimeClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ControllerRuntimeClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - obj client.Object
//   - opts ...client.CreateOption
func (_e *ControllerRuntimeClient_Expecter) Create(ctx interface{}, obj interface{}, opts ...interface{}) *ControllerRuntimeClient_Create_Call {
	return &ControllerRuntimeClient_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, obj}, opts...)...)}
}

func (_c *ControllerRuntimeClient_Create_Call) Run(run func(ctx context.Context, obj client.Object, opts ...client.CreateOption)) *ControllerRuntimeClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.CreateOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.CreateOption)
			}
		}
		run(args[0].(context.Context), args[1].(client.Object), variadicArgs...)
	})
	return _c
}

func (_c *ControllerRuntimeClient_Create_Call) Return(_a0 error) *ControllerRuntimeClient_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ControllerRuntimeClient_Create_Call) RunAndReturn(run func(context.Context, client.Object, ...client.CreateOption) error) *ControllerRuntimeClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key, obj, opts
func (_m *ControllerRuntimeClient) Get(ctx context.Context, key types.NamespacedName, obj client.Object, opts ...client.GetOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, obj)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.NamespacedName, client.Object, ...client.GetOption) error); ok {
		r0 = rf(ctx, key, obj, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ControllerRuntimeClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ControllerRuntimeClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key types.NamespacedName
//   - obj client.Object
//   - opts ...client.GetOption
func (_e *ControllerRuntimeClient_Expecter) Get(ctx interface{}, key interface{}, obj interface{}, opts ...interface{}) *ControllerRuntimeClient_Get_Call {
	return &ControllerRuntimeClient_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, key, obj}, opts...)...)}
}

func (_c *ControllerRuntimeClient_Get_Call) Run(run func(ctx context.Context, key types.NamespacedName, obj client.Object, opts ...client.GetOption)) *ControllerRuntimeClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.GetOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(client.GetOption)
			}
		}
		run(args[0].(context.Context), args[1].(types.NamespacedName), args[2].(client.Object), variadicArgs...)
	})
	return _c
}

func (_c *ControllerRuntimeClient_Get_Call) Return(_a0 error) *ControllerRuntimeClient_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ControllerRuntimeClient_Get_Call) RunAndReturn(run func(context.Context, types.NamespacedName, client.Object, ...client.GetOption) error) *ControllerRuntimeClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, list, opts
func (_m *ControllerRuntimeClient) List(ctx context.Context, list client.ObjectList, opts ...client.ListOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, list)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ObjectList, ...client.ListOption) error); ok {
		r0 = rf(ctx, list, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ControllerRuntimeClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ControllerRuntimeClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - list client.ObjectList
//   - opts ...client.ListOption
func (_e *ControllerRuntimeClient_Expecter) List(ctx interface{}, list interface{}, opts ...interface{}) *ControllerRuntimeClient_List_Call {
	return &ControllerRuntimeClient_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx, list}, opts...)...)}
}

func (_c *ControllerRuntimeClient_List_Call) Run(run func(ctx context.Context, list client.ObjectList, opts ...client.ListOption)) *ControllerRuntimeClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.ListOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.ListOption)
			}
		}
		run(args[0].(context.Context), args[1].(client.ObjectList), variadicArgs...)
	})
	return _c
}

func (_c *ControllerRuntimeClient_List_Call) Return(_a0 error) *ControllerRuntimeClient_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ControllerRuntimeClient_List_Call) RunAndReturn(run func(context.Context, client.ObjectList, ...client.ListOption) error) *ControllerRuntimeClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Scheme provides a mock function with no fields
func (_m *ControllerRuntimeClient) Scheme() *runtime.Scheme {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Scheme")
	}

	var r0 *runtime.Scheme
	if rf, ok := ret.Get(0).(func() *runtime.Scheme); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runtime.Scheme)
		}
	}

	return r0
}

// ControllerRuntimeClient_Scheme_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scheme'
type ControllerRuntimeClient_Scheme_Call struct {
	*mock.Call
}

// Scheme is a helper method to define mock.On call
func (_e *ControllerRuntimeClient_Expecter) Scheme() *ControllerRuntimeClient_Scheme_Call {
	return &ControllerRuntimeClient_Scheme_Call{Call: _e.mock.On("Scheme")}
}

func (_c *ControllerRuntimeClient_Scheme_Call) Run(run func()) *ControllerRuntimeClient_Scheme_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ControllerRuntimeClient_Scheme_Call) Return(_a0 *runtime.Scheme) *ControllerRuntimeClient_Scheme_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ControllerRuntimeClient_Scheme_Call) RunAndReturn(run func() *runtime.Scheme) *ControllerRuntimeClient_Scheme_Call {
	_c.Call.Return(run)
	return _c
}

// NewControllerRuntimeClient creates a new instance of ControllerRuntimeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewControllerRuntimeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ControllerRuntimeClient {
	mock := &ControllerRuntimeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
