// Code generated by mockery v2.53.5. DO NOT EDIT.

package vsajobtest

import (
	context "context"

	vsajob "github.com/conforma/knative-service/vsajob"
	mock "github.com/stretchr/testify/mock"
)

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// CreateVSAJob provides a mock function with given fields: ctx, snapshot
func (_m *MockExecutor) CreateVSAJob(ctx context.Context, snapshot vsajob.Snapshot) error {
	ret := _m.Called(ctx, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for CreateVSAJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, vsajob.Snapshot) error); ok {
		r0 = rf(ctx, snapshot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutor_CreateVSAJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVSAJob'
type MockExecutor_CreateVSAJob_Call struct {
	*mock.Call
}

// CreateVSAJob is a helper method to define mock.On call
//   - ctx context.Context
//   - snapshot vsajob.Snapshot
func (_e *MockExecutor_Expecter) CreateVSAJob(ctx interface{}, snapshot interface{}) *MockExecutor_CreateVSAJob_Call {
	return &MockExecutor_CreateVSAJob_Call{Call: _e.mock.On("CreateVSAJob", ctx, snapshot)}
}

func (_c *MockExecutor_CreateVSAJob_Call) Run(run func(ctx context.Context, snapshot vsajob.Snapshot)) *MockExecutor_CreateVSAJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vsajob.Snapshot))
	})
	return _c
}

func (_c *MockExecutor_CreateVSAJob_Call) Return(_a0 error) *MockExecutor_CreateVSAJob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutor_CreateVSAJob_Call) RunAndReturn(run func(context.Context, vsajob.Snapshot) error) *MockExecutor_CreateVSAJob_Call {
	_c.Call.Return(run)
	return _c
}

// WithConfigMapName provides a mock function with given fields: configMapName
func (_m *MockExecutor) WithConfigMapName(configMapName string) vsajob.Executor {
	ret := _m.Called(configMapName)

	if len(ret) == 0 {
		panic("no return value specified for WithConfigMapName")
	}

	var r0 vsajob.Executor
	if rf, ok := ret.Get(0).(func(string) vsajob.Executor); ok {
		r0 = rf(configMapName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vsajob.Executor)
		}
	}

	return r0
}

// MockExecutor_WithConfigMapName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithConfigMapName'
type MockExecutor_WithConfigMapName_Call struct {
	*mock.Call
}

// WithConfigMapName is a helper method to define mock.On call
//   - configMapName string
func (_e *MockExecutor_Expecter) WithConfigMapName(configMapName interface{}) *MockExecutor_WithConfigMapName_Call {
	return &MockExecutor_WithConfigMapName_Call{Call: _e.mock.On("WithConfigMapName", configMapName)}
}

func (_c *MockExecutor_WithConfigMapName_Call) Run(run func(configMapName string)) *MockExecutor_WithConfigMapName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockExecutor_WithConfigMapName_Call) Return(_a0 vsajob.Executor) *MockExecutor_WithConfigMapName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutor_WithConfigMapName_Call) RunAndReturn(run func(string) vsajob.Executor) *MockExecutor_WithConfigMapName_Call {
	_c.Call.Return(run)
	return _c
}

// WithNamespace provides a mock function with given fields: namespace
func (_m *MockExecutor) WithNamespace(namespace string) vsajob.Executor {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for WithNamespace")
	}

	var r0 vsajob.Executor
	if rf, ok := ret.Get(0).(func(string) vsajob.Executor); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vsajob.Executor)
		}
	}

	return r0
}

// MockExecutor_WithNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithNamespace'
type MockExecutor_WithNamespace_Call struct {
	*mock.Call
}

// WithNamespace is a helper method to define mock.On call
//   - namespace string
func (_e *MockExecutor_Expecter) WithNamespace(namespace interface{}) *MockExecutor_WithNamespace_Call {
	return &MockExecutor_WithNamespace_Call{Call: _e.mock.On("WithNamespace", namespace)}
}

func (_c *MockExecutor_WithNamespace_Call) Run(run func(namespace string)) *MockExecutor_WithNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockExecutor_WithNamespace_Call) Return(_a0 vsajob.Executor) *MockExecutor_WithNamespace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutor_WithNamespace_Call) RunAndReturn(run func(string) vsajob.Executor) *MockExecutor_WithNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
