// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CloudEventsClient is an autogenerated mock type for the CloudEventsClient type
type CloudEventsClient struct {
	mock.Mock
}

type CloudEventsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CloudEventsClient) EXPECT() *CloudEventsClient_Expecter {
	return &CloudEventsClient_Expecter{mock: &_m.Mock}
}

// StartReceiver provides a mock function with given fields: ctx, fn
func (_m *CloudEventsClient) StartReceiver(ctx context.Context, fn interface{}) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for StartReceiver")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CloudEventsClient_StartReceiver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartReceiver'
type CloudEventsClient_StartReceiver_Call struct {
	*mock.Call
}

// StartReceiver is a helper method to define mock.On call
//   - ctx context.Context
//   - fn interface{}
func (_e *CloudEventsClient_Expecter) StartReceiver(ctx interface{}, fn interface{}) *CloudEventsClient_StartReceiver_Call {
	return &CloudEventsClient_StartReceiver_Call{Call: _e.mock.On("StartReceiver", ctx, fn)}
}

func (_c *CloudEventsClient_StartReceiver_Call) Run(run func(ctx context.Context, fn interface{})) *CloudEventsClient_StartReceiver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *CloudEventsClient_StartReceiver_Call) Return(_a0 error) *CloudEventsClient_StartReceiver_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CloudEventsClient_StartReceiver_Call) RunAndReturn(run func(context.Context, interface{}) error) *CloudEventsClient_StartReceiver_Call {
	_c.Call.Return(run)
	return _c
}

// NewCloudEventsClient creates a new instance of CloudEventsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloudEventsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloudEventsClient {
	mock := &CloudEventsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
