apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  # These would be present already in a Konflux cluster
  - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
  - https://raw.githubusercontent.com/konflux-ci/application-api/refs/heads/main/manifests/application-api-customresourcedefinitions.yaml
