# Copyright The Conforma Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: License Header Check

on:
  pull_request:
    branches: [ main ]

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: Check License Headers
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'
        
    - name: Check License Headers
      run: |
        echo "🔍 Checking license headers..."
        go run -modfile tools/go.mod github.com/google/addlicense -check -ignore '.github/ISSUE_TEMPLATE/**' -ignore '.github/PULL_REQUEST_TEMPLATE/**' -ignore '.github/dependabot.yml' -ignore 'vendor/**' -ignore 'node_modules/**' -ignore '*.md' -ignore '*.json' -ignore 'go.mod' -ignore 'go.sum' -ignore 'LICENSE' -ignore 'ko.yaml' -ignore '.ko.yaml' -ignore '.golangci.yml' -c 'The Conforma Contributors' -s -y 2025 .
          
    - name: Show license header format on failure
      if: failure()
      run: |
        echo "💥 Some files are missing license headers!"
        echo ""
        echo "📋 Expected license header format:"
        echo ""
        echo "For Go files (.go):"
        echo "// Copyright The Conforma Contributors"
        echo "//"
        echo "// Licensed under the Apache License, Version 2.0 (the \"License\");"
        echo "// you may not use this file except in compliance with the License."
        echo "// You may obtain a copy of the License at"
        echo "//"
        echo "//      http://www.apache.org/licenses/LICENSE-2.0"
        echo "//"
        echo "// Unless required by applicable law or agreed to in writing, software"
        echo "// distributed under the License is distributed on an \"AS IS\" BASIS,"
        echo "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied."
        echo "// See the License for the specific language governing permissions and"
        echo "// limitations under the License."
        echo "//"
        echo "// SPDX-License-Identifier: Apache-2.0"
        echo ""
        echo "For YAML/Shell files (.yaml, .yml, .sh, Makefile):"
        echo "# Copyright The Conforma Contributors"
        echo "#"
        echo "# Licensed under the Apache License, Version 2.0 (the \"License\");"
        echo "# you may not use this file except in compliance with the License."
        echo "# You may obtain a copy of the License at"
        echo "#"
        echo "#      http://www.apache.org/licenses/LICENSE-2.0"
        echo "#"
        echo "# Unless required by applicable law or agreed to in writing, software"
        echo "# distributed under the License is distributed on an \"AS IS\" BASIS,"
        echo "# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied."
        echo "# See the License for the specific language governing permissions and"
        echo "# limitations under the License."
        echo "#"
        echo "# SPDX-License-Identifier: Apache-2.0"
        echo ""
        echo "To fix missing headers, you can run:"
        echo "make license-add"
